"use client";

import Image, { StaticImageData } from "next/image";
import React, { useState } from "react";
import { useKeenSlider } from "keen-slider/react";
import "keen-slider/keen-slider.min.css";

import testimonialPerson1 from "../../../public/testimonial_Person_1.png";
import testimonialPerson2 from "../../../public/testimonial_Person_2.png";
import testimonialQuoteIcon from "../../../public/testimonial_Quote_Icon.svg"

interface Testimonial {
  iconQuote:  StaticImageData | string;
  quote:string;
  text: string;
  author: string;
  role: string;
  company: string;
  companyColor: string;
  imageSrc: StaticImageData;
  alt: string;
}

const testimonials: Testimonial[] = [
  {
    iconQuote: testimonialQuoteIcon,
    quote: "Time Saving & Editing",
    text: "Before Verbite, I spent hours editing AI output. It was exhausting. Verbite is different – the content is high-quality and actually ready to use. It's saved me countless hours each week and freed me up for more strategic tasks.",
    author: "Name Surname",
    role: "SEO Specialist",
    company: "@ Growth Agency Pro",
    companyColor: "text-purple-300",
    imageSrc: testimonialPerson1,
    alt: "Portrait of testimonial author",
  },
  {
    iconQuote: testimonialQuoteIcon,
    quote: "Time Saving & Editing",
    text: "We needed our articles to rank, but traditional writing was too slow, and other AI was too generic. Verbite’s SEO focus is a game-changer. Since implementing content generated by Verbite, we’ve seen a significant jump in keyword rankings and organic traffic.",
    author: "Sarah Chen",
    role: "Content Manager",
    company: "@ Innovate Solutions",
    companyColor: "text-green-300",
    imageSrc: testimonialPerson2,
    alt: "Portrait of testimonial author",
  },
];
const TestimonialsSlider = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [sliderRef] = useKeenSlider<HTMLDivElement>({
    loop: true,
    slideChanged(s) {
      setCurrentSlide(s.track.details.rel);
    },
    slides: {
      perView: 1,
      spacing: 16,
    },
    breakpoints: {
      "(min-width: 1024px)": {
        slides: { perView: 2, spacing: 24 },
      },
    },
    
  });

  return (
    <section className="bg-black text-white px-6 py-20 lg:px-24">
      <h2 className="text-3xl lg:text-4xl font-semibold text-center mb-3">
        Testimonials
      </h2>
      <p className="text-gray-400 text-center max-w-2xl mx-auto mb-10">
        Not just text, but a complete, publish-ready content – thoroughly
        researched, well-structured, and trustworthy. Every time.
      </p>

      <div ref={sliderRef} className="keen-slider">
        {testimonials.map((t, index) => (
          <div
          key={index}
          className="keen-slider__slide flex px-0 lg:w-full h-[500px] space-x-4"
        >
          {/* Text section */}
          <div className="flex-[1.05] bg-zinc-900 rounded-xl h-full flex flex-col justify-between p-4">
            <div className="p-12">
              <Image src={t.iconQuote} alt="iconQuote" className="w-12"/>
              <h3 className="text-3xl font-semibold mt-4">{t.quote}</h3>
              <p className="text-xl text-gray-400 mt-2">{t.text}</p>
            <div className="mt-6">
              <p className="font-semibold">{t.author}</p>
              <p className="text-xl text-gray-400">
                {t.role} <span className={`${t.companyColor}`}>{t.company}</span>
              </p>
            </div>
            </div>
          </div>
        
          {/* Image section */}
          <div className="flex-[0.95] h-full">
            <Image
              src={t.imageSrc}
              alt={t.alt}
              className="rounded-xl h-full w-[70%] object-cover"
            />
          </div>
        </div>
        
        ))}
      </div>

      {/* Dot indicators */}
      <div className="flex justify-center gap-3 mt-6">
        {testimonials.map((_, idx) => (
          <span
            key={idx}
            className={`h-[4px] rounded-full transition-all duration-300 ${
              currentSlide === idx
                ? "bg-purple-400 w-8"
                : "bg-gray-600 w-6"
            }`}
          />
        ))}
      </div>
    </section>
  );
};

export default TestimonialsSlider;

